dist: trusty

language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

before_script:
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run --coverage --coverage-xml --coverage-html
  - vendor/bin/phpstan analyse src --level=1 --no-interaction --no-progress
